---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://helm.linkerd.io/stable
      chart: linkerd2
      version: 2.9.4
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: linkerd-certs
      valuesKey: ca.crt
      targetPath: global.identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.key
      targetPath: identity.issuer.tls.keyPEM
  values:
    installNamespace: false
    identity:
      issuer:
        crtExpiry: "2022-08-10T04:32:35Z"
    enableEndpointSlices: true
    enablePodAntiAffinity: true
    proxy:
      resources:
        cpu:
          request: 100m
        memory:
          limit: 250Mi
          request: 20Mi
    controllerReplicas: 2
    controllerResources: &controller_resources
      cpu: &controller_resources_cpu
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    destinationResources: *controller_resources
    identityResources:
      cpu: *controller_resources_cpu
      memory:
        limit: 250Mi
        request: 10Mi
    heartbeatResources: *controller_resources
    proxyInjectorResources: *controller_resources
    webhookFailurePolicy: Fail
    spValidatorResources: *controller_resources
