---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 4.16.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.12.1
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.12.1
    configInline:
      peers:
      - peer-address: "${ROUTER_IP}"
        peer-asn: "${BGP_PEER_ASN}"
        my-asn: "${BGP_MY_ASN}"
      address-pools:
      - name: default
        protocol: bgp
        addresses:
        - "${METALLB_LB_RANGE}"
