
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 1.8.34
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
      interval: 5m
  values:
    extraEnvVars:
      ServerIP: "${CLUSTER_LB_PIHOLE}"
      TZ: "America/Denver"
    image:
      repository: pihole/pihole
      tag: v5.8
      doh:
        enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
    serviceDns:
      annotations:
          metallb.universe.tf/address-pool: default
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "${CLUSTER_LB_PIHOLE}"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceWeb:
      annotations:
          metallb.universe.tf/address-pool: default
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "${CLUSTER_LB_PIHOLE}"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc