---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homer
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: b4bz/homer
      tag: 21.07.1
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
            grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port; 
          kubernetes.io/ingress.class: "nginx"
          external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
          cert-manager.io/issuer: cf-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
        hosts:
        - host: "homer.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "homer.${SECRET_DOMAIN}"
          secretName: homer-tls
    persistence:
      config:
        enabled: true
        existingClaim: homer-config
        mountPath: /www/assets
