---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: spx01/blocky
      tag: v0.19
    controller:
      strategy: RollingUpdate
      replicas: 3
    env:
      TZ: "America/Denver"
    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${CLUSTER_LB_BLOCKY}"
        externalTrafficPolicy: Local
        annotations:
              metallb.universe.tf/allow-shared-ip: blocky-svc
        ports:
          dns-tcp:
            enabled: true
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${CLUSTER_LB_BLOCKY}"
        externalTrafficPolicy: Local
        annotations:
              metallb.universe.tf/allow-shared-ip: blocky-svc
        ports:
          dns-udp:
            enabled: true


    prometheus:
      serviceMonitor:
        enabled: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    config: |
      upstream:
        default:
        - 192.168.5.1
        #externalResolvers:
        #- tcp-tls:4838af.dns1.nextdns.io:853
        #- tcp-tls:4838af.dns2.nextdns.io:853
        #- https://dns.google/dns-query
        #- https://cloudflare-dns.com/dns-query
      blocking:
        blackLists:
          ads:
          # https://oisd.nl/
          - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://mirror1.malwaredomains.com/files/justdomains
          - http://sysctl.org/cameleon/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - whitelist.txt
        clientGroupsBlock:
          default:
          - ads
      caching:
        prefetching: true
      clientLookup:
        upstream: udp:192.168.5.1
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 300Mi
