apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-user
  namespace: networking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: public-ip-patcher
subjects:
- kind: ServiceAccount
  name: flux-user
  namespace: networking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: public-ip-patcher
rules:
- apiGroups: ["helm.toolkit.fluxcd.io"] # "" indicates the core API group
  resources: ["*"]
  resourceNames: ["ingress-nginx"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["home-public-ip"]
  verbs: ["*"]
---  
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ip-updater
  namespace: networking
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          serviceAccountName: flux-user
          containers:
          - name: whatismyip
            image: jukie/public-ip-updater:v3
            imagePullPolicy: IfNotPresent
            command:
            - /entrypoint.sh
          restartPolicy: OnFailure
