---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: ${BOOTSTRAP_METALLB_LB_RANGE}
  INGRESS_NGINX_LB: ${BOOTSTRAP_INGRESS_NGINX_LB}
  ROUTER_IP: ${BOOTSTRAP_ROUTER_IP}
  BGP_PEER_ASN: "${BOOTSTRAP_BGP_PEER_ASN}"
  BGP_MY_ASN: "${BOOTSTRAP_BGP_MY_ASN}"
