---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
  - "${SECRET_DOMAIN}"
  - "*.${SECRET_DOMAIN}"
  duration: 168h
  renewBefore: 24h