---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://openebs.github.io/charts
      chart: openebs
      version: 2.12.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    release:
      version: "2.12.0"
    legacy:
      enabled: true
    varDirectoryPath:
      baseDir: "/var/openebs"

    provisioner:
      enabled: true
      image: "openebs/openebs-k8s-provisioner"
      imageTag: "2.12.0"
      resources:
         limits:
           cpu: 1000m
           memory: 1Gi
         requests:
           cpu: 500m
           memory: 1Gi
    localprovisioner:
      enabled: false

    snapshotOperator:
      enabled: false

    ndm:
      enabled: true
      resources:
         limits:
           cpu: 1000m
           memory: 1Gi
         requests:
           cpu: 500m
           memory: 1Gi
    ndmOperator:
      enabled: true
      image: "openebs/node-disk-operator"
      imageTag: "1.6.1"
      resources:
         limits:
           cpu: 1000m
           memory: 1Gi
         requests:
           cpu: 500m
           memory: 1Gi
    webhook:
      enabled: true
      image: "openebs/admission-server"
      imageTag: "2.12.0"
      resources: 
         limits:
           cpu: 500m
           memory: 1Gi
         requests:
           cpu: 250m
           memory: 500Mi
    analytics:
      enabled: false
    cstor:
      enabled: true
      openebsNDM:
        enabled: false
    openebs-ndm:
      enabled: true
      varDirectoryPath:
        baseDir: "/var/openebs"
