# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:XTkhJPXC7KTAq8g08L6okqurq89Jy2zPOdX7Wes9wXGp2bNTje2n2Q==,iv:lQOngsNa5fFJjVb6T1+L6z1lfUgkIT0nfwC44ae9QNM=,tag:tevxrbm4tuyaaohsh1mnQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-22T04:43:25Z"
    mac: ENC[AES256_GCM,data:9jRN4LYiy9tBLYub+UoD9EacLmNvdoJWEN6k0qvy4BPYCC58rWaJEYlDalTPCl73beuIndqm6UM/Fixeysa+D02gIGWQGZh2W0AAOjE/4WVmrXfK4u/dBVaTR1swTlH4QkYXx/Os73LUutuABDBNNOp1ABwS7EzquOjfBnS0xLY=,iv:tv/NAw71RPyT4/sN/tH5JaXh7pGyIFpDKobAd+rMXdM=,tag:tOi817mkbmSJebIhqjCjnQ==,type:str]
    pgp:
        - created_at: "2021-04-22T04:43:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0D75ldA2vu6AQ/6AkW5P7QF1axttgo5NCwmHsqubKQYKAd2XYrOc2X+wyjj
            nqgy1yeoF5VjRFA94Ogpv1leDrA/Yx9L6xvLFGyt9OY2tr85jvJfWH2s4jvkdGir
            FCB29D1ixVnjGQTA+zZMjE0KseY5b/GacBPG3fUbX8qyKNnyHpJr+ez34r2cQ9G1
            1HubGlFl2VRse5k4yVwtxwh3HEiLEofC9BPM1HZFJmi29XzLX+T22LGzr8UbWPa1
            h7W3W1jdEOZ+XM5GnmtAp15xk1dgSYTxbLKMWmX6dSSFA7hUg3+dMuab4pjuM6qX
            YhqJduhUFPUJVBJid8JeM+kl0a3FMkao5+r3iMCIM7xHnDJE28XzL3vgMeWUmR3y
            MFONMryRhrZrfhMcYM/WdS/s4N7ykmJnnn/0Mo5q5mkuzzP+r/PnJUD2GqbsnTT8
            vKgJoR3N335mv1vyZOw1FX6pLlmGEBBtvOelOrE8zo0M4ETMmid3KC43IEtGL+6e
            tRS6qpaVvYv/PU+UlV3zmi/IqIQaV/lteC5h45YYPLDnzR9hFO/niusDI8VPyjWl
            6j2lxwXdHhEKmYdVIIelgFo4x62Tz2Itdza50R1rMLpSPMXezYrC7t2/DauUZaGz
            WYHw0tg62axoE//Q790Lm24bw9aU8vmy2NvCkkphykTmq0d7hYnu5gn+nTjNjVzS
            XgGlR7JdApcMRn8zwG/1rrzODhA18uEDLhtl8vxMqZeHsL95M/ERNHpQcolqsUXU
            nJR5aSeucAbEgJudkLVS2LVajEfJfNHO2X4UjdJ6UD+Qay8N86QvLWvu8nn/2KI=
            =iIii
            -----END PGP MESSAGE-----
          fp: 9D9249FFBCA99FBCC6A8D85642D1488E80A12CB7
        - created_at: "2021-04-22T04:43:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Kwrtfq3fwwAQ//YcPvtvuqklw0bz47Lj/vQlZWKlemSWmLd8hC4oK+EH5F
            bf0WICKt8VgYyxZuXFeLCxT9N9QPBfsLpb83oY4Y7QJorMFW42iGQ8n8c0Yk8Pzm
            LNprUAu/Ia0v6gtwWFTTK3MtE9vhqz1r9ezvcgLT6vbBOKPxLv48r9oIWQ07r5/u
            XzxKAJZ3MTITIhkkxIOD6PCenPFFUgRqwSUp9J6EXPz9aSwoW3sGgt6tLwr2YFmB
            V2q7IOfXa3jaObfSZOZS3Q9lnpgxi8Q45HDxa5edB6zk9EDJPy39DcgBfgQevf5L
            pR2qW5Df6+G+FGVrELxo5d8AQz12A+MTWQaDAf3mGAlQtKfEOuO8xFLWjJcXyerD
            kmM1uHIMGl6Q1wib09R/99QwQMdTi4G5AB7IPuIvbPO9c3+Y1vPnPSIlZGXSkwcF
            KeBb+DfgG9qoA4w877fa8AfcG+21i6L7PM3pXziNkbUa/Df6FSGm6U8cR+yEQoiI
            DG7dSEUHWmqsp2M0nlQePRgv2QXBySVoJUPTg9fRkdslVRcLg2+52m4SPh+RxeV7
            I2tMaTL1Xj6kVCJYYEI9SpU9JbJzwxwueRqu+l/bHV6IgxCZ6CTQOlW9qAVv0VKR
            LvN+HGjTHKVAc3BRNAl1lni9ljaD0XEK9hD6sCFIlO+nmPjHNgIX5CJLI5dwPnnS
            XgHjSpscsSbefhe6nPgRUuDN+Vi7QLzDUm4tTlOoybAWjiwd+acGSgseV2DAxYJw
            u1XM9NTPyLfVWeEm2aB6WQ3A/3i8PNR++n5Ac2f/zLs4UqGlUwUKq+HAmF4DRTc=
            =rsP7
            -----END PGP MESSAGE-----
          fp: E41FBF6FE4D325C299AA8AD6735F040570428580
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
