---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  annotations:
    linkerd.io/inject: disabled
  labels:
    config.linkerd.io/admission-webhooks: disabled
    linkerd.io/control-plane-ns: linkerd