
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 5.4.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: k8s.gcr.io
      repository: external-dns/external-dns
      tag: v0.9.0
    logLevel: debug
    provider: cloudflare
    cloudflare:
      apiToken: ${SECRET_CLOUDFLARE_TOKEN}
      proxied: true
    policy: sync
    zoneIdFilters: 
    - ${SECRET_CLOUDFLARE_ZONE}
    domainFilters:
    - ${SECRET_DOMAIN}
    registry: "txt"
    createSecret: true
    crd:
      create: true
    metrics:
      enabled: false
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi
